apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    #cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - DOMAIN_NAME
    secretName: aks-ingress-tls
  rules:
  - host: DOMAIN_NAME
    http:
      paths:
      - path: /(.*)
        backend:
          serviceName: api
          servicePort: 80
---
#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    io.kompose.service: api
#  name: api-egress
#spec:
#  type: LoadBalancer
#  loadBalancerIP: PUBLIC_IP
#  ports:
#  - name: http
#    port: 80
#    nodePort: 30000
#    targetPort: 8080
#  selector:
#    app: api
#---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: api
  name: api
spec:
  type: ClusterIP
  ports:
  - name: zmq1
    port: 6143
  - name: zmq2
    port: 6144
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - env:
        - name: HOST_ADDR
          value: 0.0.0.0:8080
        - name: PROFILING
          value: "false"
        - name: ZMQ_REP_ADDR
          value: tcp://*:6144
        - name: ZMQ_REQ_ADDR
          value: tcp://*:6143
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
        image: oneseismic.azurecr.io/api:latest
        imagePullPolicy: Always
        envFrom:
          - secretRef:
             name: mysecret
        name: api
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fragment
  name: fragment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fragment
  template:
    metadata:
      labels:
        app: fragment
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - args:
        - oneseismic-fragment
        - --source
        - tcp://manifest:6142
        - --sink
        - tcp://api:6144
        - --control
        - tcp://0.0.0.0:6141
        - --fail
        - tcp://0.0.0.0:6140
        - --account
        - $(AZURE_STORAGE_ACCOUNT)
        - --key
        - $(AZURE_STORAGE_ACCESS_KEY)
        image: oneseismic.azurecr.io/base:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
        envFrom:
          - secretRef:
              name: mysecret
        name: fragment
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: manifest
  name: manifest
spec:
  type: ClusterIP
  ports:
  - name: zmq
    port: 6142
  selector:
    app: manifest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: manifest
  name: manifest
spec:
  selector:
    matchLabels:
      app: manifest
  template:
    metadata:
      labels:
        app: manifest
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - args:
        - oneseismic-manifest
        - --source
        - tcp://api:6143
        - --sink
        - tcp://*:6142
        - --control
        - tcp://0.0.0.0:6141
        - --fail
        - tcp://0.0.0.0:6140
        - --account
        - $(AZURE_STORAGE_ACCOUNT)
        - --key
        - $(AZURE_STORAGE_ACCESS_KEY)
        image: oneseismic.azurecr.io/base:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
        envFrom:
          - secretRef:
             name: mysecret
        name: manifest
